name: Lint

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: 3.1.1
  NODE_VERSION: 18.17.1

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpq-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Uninstall json
        run: gem uninstall json -a --quiet

      - name: Install json -v 2.6.3
        run: gem install json -v 2.6.3

      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci
        name: Install JS deps

      - run: bundle exec rubocop -P
        name: Lint Ruby files

      - run: bundle exec mdl *.md
        name: Lint Markdown files

      - run: bundle exec erblint app/views/**/*.erb
        name: Lint ERB files

      - run: npm run stylelint
        name: Lint SCSS files

      - run: npm run lint
        name: Lint JS files